### ISSUE TITLE
Segfault with v0.11.0

### ISSUE THREAD

**Issue by howetuft** [ospray/ospray_studio#16]
Hello,
The simple project here attached used to work perfectly with v0.9.0, but now generates a segmentation fault with v0.11.0. Could you please tell what is wrong? Many thanks in advance!

[Project.zip](https://github.com/ospray/ospray_studio/files/9178173/Project.zip)

**Comment by BruceCherniak** [comment]
Hi,

Apologies.  v0.11.0 unintentionally broke backward compatibility with some scene files, while gaining new abilities to hold more camera information.  There is a bugfix release v0.11.1 coming out very soon (hopefully pushed today).

The new release will not crash on these files, yet the default camera position may be reset vs previous versions of Studio.  Simply load the scene, set the default camera and then re-save the scene.

**Comment by howetuft** [comment]
Hello,
Thank you for your reactivity! Please let me know when the patch is applied.
I understand that previous syntax for camera is no more supported, is it? Where can I find the documentation of the new syntax (I write an exporter)? Many thanks in advance...

**Comment by BruceCherniak** [comment]
Hi,

Until I can get the v0.11.1 release out, I have edited your .sg file (attached) to make it compatible with the new format. To do this, I have simply replaced the "camera" object of your file with one of the new format.  This will work in the v0.11.0 release.

In general, the camera is now specified by a single (more standard) `CameraToWorld` affine transform, rather than the `centerTranslation`, `rotation`, and `translation`.

Better documentation and more features are forthcoming, but this hopefully gets you back up and running same as before.

[Project.sg.txt](https://github.com/ospray/ospray_studio/files/9182146/Project.sg.txt)

**Comment by howetuft** [comment]
Thank you, I'll modify my exporter accordingly!

**Comment by BruceCherniak** [comment]
Does this resolve your issue?

Also, please note that the bugfix release v0.11.1 was just posted (https://github.com/ospray/ospray_studio/releases/tag/v0.11.1) to resolve issues with other .sg files you may have.

**Comment by howetuft** [comment]
Yes, thank you, I've modified my exporter and now it seems to work!

(though I've got another error with sunSky light now, but I'll open a dedicated ticket later)

**Comment by BruceCherniak** [comment]
Glad we were able to get that resolved quickly.

Is the sunSky now too bright, by any chance?  If so, please note that **default intensity is now 0.025**, per the change in OSPRay v2.6.0 (https://github.com/ospray/ospray/releases/tag/v2.6.0).  If it's something else, I'm happy to help on a new dedicated ticket.
