### ISSUE TITLE
Sunsky raises error (v0.11.1)

### ISSUE THREAD

**Issue by howetuft** [ospray/ospray_studio#17]
Hello,

The attached file merely includes a sunsky and used to work well with v0.9.0. With v0.11.1, however, it will generate an error:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Node::valueAs(): Incorrect type queried for Any
  Node::name() = up
  Node::type() = PARAMETER
  Node::subType() = vec3f
  Node::value() = Any : (currently holds value of type) --> rkcommon::math::vec_t<int, 3, false>
  queried type = rkcommon::math::vec_t<float, 3, false>
```
[Sunsky.zip](https://github.com/ospray/ospray_studio/files/9186066/Sunsky.zip)

Could you please tell me what's wrong with it? Thanks!

**Comment by BruceCherniak** [comment]
The error is caused because in the Sunsky.sg file, `up` is specified as `[0, 1, 0]` which gets interpreted as a `vec3i` and not `vec3f`.  I notice the same is true of `right`.  The `Any` class is very strict on type and does not implicitly convert the int types to float.

Not entirely sure how this worked back in v0.9.0, unless we mistakenly converted on importing these json values - we try to be quite literal on the import.

In any regard, simply change the .sg to `[0.0, 1.0, 0.0]` and it should work.

**Comment by BruceCherniak** [comment]
Ah yes, here are the two lines of code in your branch that cause this:
- https://github.com/howetuft/FreeCAD-render/blob/7941c42211dafa1fb686896571697d8aa5920e62/Render/renderers/Ospray.py#L315
- https://github.com/howetuft/FreeCAD-render/blob/7941c42211dafa1fb686896571697d8aa5920e62/Render/renderers/Ospray.py#L323

**Comment by howetuft** [comment]
Yes, it works again, thank you!
