### ISSUE TITLE
Ospray Studio not using available ARC 750?

### ISSUE THREAD

**Issue by ergo70** [ospray/ospray_studio#26]
I have a i9 with integrated UHD 770 graphics and an ARC 750 running Windows 11 Professional. Ospray Studio does use the i9 and the UHD graphics, but not the ARC 750. Can this be set somewhere?

I have tried to run it with --osm:device=cpu|gpu|default but this only yields "unknown directive" errors.

**Comment by johguenther** [comment]
Did you also pass `--osp:load-modules=gpu` before `--osp:device=gpu`?

**Comment by ergo70** [comment]
No, thank you for the hint. But now I get:
ISPCRT Error (1): there should be only one Intel driver in the system
and Ospray Studio does not start.
I have installed the latest ARC Driver 31.0.101.4972, my own SYCL / DPC++ code works fine and I can choose the CPU, UHD770, and ARC 750 as targets.

**Comment by johguenther** [comment]
Fixing this will take a bit: ISPCRT currently supports only a single Intel driver https://github.com/ispc/ispc/blob/main/ispcrt/detail/gpu/GPUDevice.cpp#L1754

Until a proper fix you could patch ISPCRT in the file above (and have `BUILD_ISPCRT_FROM_SOURCE=ON`) to always select the first or second driver (OSPRay won't run on the UHD770, because it does not have HW ray tracing).
Or disable the UHD770 (driver or BIOS)...

**Comment by ergo70** [comment]
Ah, that makes sense. Thank you!

**Comment by johguenther** [comment]
Released v1.0 uses OSPRay v3.1, which uses ISPCRT v1.23, which solves the issue: set env var `ISPCRT_GPU_DRIVER=0` (or 1) to select which GPU to use.
